/*
 * ADAM — بذرة إضافية للمكتبة الطبية (30 مقالة جديدة)
 *
 * نفس قواعد الملف الأساسي med-library-seed.js بالظبط: دي مسودات
 * تثقيف صحي عام (status: draft) — مش هتوصل لأي عميل إلا بعد ما
 * طبيب أو صيدلي مرخّص يراجعها ويعدّلها ويوافق عليها من داخل التطبيق.
 * مفيش فيها جرعات دوائية ولا تشخيص لحالة بعينها، ومش بديل عن الكشف.
 *
 * Same rules as med-library-seed.js: general health-education drafts
 * (status: draft) only — never shown to clients until a licensed
 * doctor/pharmacist reviews and approves them in the app. No drug
 * dosing, no individual diagnosis, never a substitute for a consultation.
 * Topics deliberately avoid repeating the 31 base articles; where a
 * subject overlaps (concussion, heat, NSAIDs, stress fractures, RED-S,
 * ACL) these take a different, complementary angle.
 */

export const MED_LIBRARY_SEED_EXTRA = [

  /* ==================== طبيب طب رياضي ==================== */
  {
    specialty: 'sports_medicine',
    category: 'redflag',
    title: 'الإسعاف الأولي لإصابات الملاعب — إمتى لازم تروح الطوارئ؟',
    titleEn: 'Pitch-side first aid — when to go to the emergency department',
    body: 'أول دقايق بعد الإصابة بتفرق كتير. القاعدة الأولى: وقّف النشاط فورًا ومتحاولش "تكمّل على الإصابة". في الإصابات البسيطة (كدمة أو التواء خفيف) بنطبّق مبادئ الإسعاف الأولي المعروفة زي بروتوكول POLICE الموجود في المكتبة: حماية المنطقة، ثلج ملفوف في فوطة 15-20 دقيقة، رباط ضاغط خفيف، ورفع الطرف، وبعد أول يوم أو اتنين حركة خفيفة في حدود مفيهاش ألم.\n\nروح الطوارئ فورًا (أو اطلب الإسعاف على 123) لو ظهر أي من دول: عدم القدرة على الوقوف على الرجل أو تحريك الطرف خالص، تشوّه واضح أو عظمة باينة أو جرح عميق، تنميل أو برودة أو ازرقاق في الطرف تحت الإصابة، خبطة في الراس معاها فقدان وعي أو قيء أو تلخبط، أي إصابة في الرقبة أو الضهر (متحركش المصاب واستنى الإسعاف)، ألم صدر أو ضيق نفس، ألم بطن شديد بعد اصطدام، أو نزيف مش بيقف بالضغط المباشر.\n\nوفي الانتظار: متحاولش ترجّع مفصل مخلوع مكانه، متعملش تدليك أو حرارة على إصابة جديدة، ومتاخدش مسكنات قوية قبل ما الطبيب يقيّم الحالة عشان متخبيش الأعراض. وأي إصابة "بسيطة" متحسنتش بوضوح خلال أيام قليلة محتاجة كشف.',
    bodyEn: 'The first minutes after an injury matter. Rule one: stop the activity immediately and do not try to "play through it". For minor injuries (a bruise or a mild sprain) the usual first-aid principles apply, such as the POLICE protocol found elsewhere in this library: protect the area, apply ice wrapped in a towel for 15–20 minutes, use a light compression bandage, elevate the limb, and after the first day or two start gentle movement within pain-free limits.\n\nGo to the emergency department immediately (or call an ambulance — 123 in Egypt) if any of these appear: complete inability to stand on the leg or move the limb, obvious deformity, visible bone or a deep wound, numbness, coldness or blue discolouration below the injury, a head knock with loss of consciousness, vomiting or confusion, any neck or back injury (do not move the person — wait for the ambulance), chest pain or shortness of breath, severe abdominal pain after a collision, or bleeding that does not stop with direct pressure.\n\nWhile waiting: do not try to put a dislocated joint back, do not massage or apply heat to a fresh injury, and avoid strong painkillers before a doctor has assessed the injury so symptoms are not masked. Any "minor" injury that has not clearly improved within a few days needs a medical assessment.'
  },
  {
    specialty: 'sports_medicine',
    category: 'redflag',
    title: 'بعد خبطة الراس — علامات الخطر في أول 48 ساعة',
    titleEn: 'After a head knock — danger signs in the first 48 hours',
    body: 'المقالة دي مكمّلة لمقالة ارتجاج المخ في المكتبة: بعد أي خبطة في الراس حتى لو الرياضي "كويس"، الأفضل ميفضلش لوحده في أول 24 ساعة، وميسوقش، وميشربش كحول ولا ياخد منومات. الراحة بتكون راحة نسبية قصيرة (يوم أو اتنين) من الشاشات والمجهود، وبعدها رجوع تدريجي للنشاط اليومي حسب الأعراض وتعليمات الطبيب.\n\nعلامات بتستدعي الطوارئ فورًا: صداع بيزيد باستمرار، قيء متكرر، تشنجات، نعاس زايد أو صعوبة في الإفاقة، تلخبط أو تصرفات غريبة أو عدم التعرف على الناس، كلام متلخبط، ضعف أو تنميل في الإيدين أو الرجلين، اختلاف حجم حدقتي العين أو زغللة، خروج سائل شفاف أو دم من الأنف أو الودن، أو ألم في الرقبة. الرياضي اللي بياخد أدوية سيولة، أو الكبير في السن، أو الطفل، محتاج تقييم طبي بعتبة أقل بكتير.\n\nمتاخدش أي مسكن من غير ما تسأل الطبيب أو الصيدلي، لأن بعض المسكنات مش مفضّلة في الأيام الأولى بعد إصابة الراس. والرجوع للتمرين بيكون بخطة مراحل وبموافقة طبية، مش لمجرد إن الصداع راح.',
    bodyEn: 'This article complements the concussion article in the library. After any head knock — even if the athlete "seems fine" — they should ideally not be left alone for the first 24 hours, should not drive, and should avoid alcohol and sleeping pills. Rest means short, relative rest (a day or two) from screens and exertion, followed by a gradual return to daily activity guided by symptoms and the doctor\'s instructions.\n\nSigns that need the emergency department immediately: a headache that keeps getting worse, repeated vomiting, a seizure, increasing drowsiness or difficulty waking, confusion, strange behaviour or not recognising people, slurred speech, weakness or numbness in the arms or legs, unequal pupils or blurred/double vision, clear fluid or blood from the nose or ears, or neck pain. Athletes on blood thinners, older adults and children need medical assessment at a much lower threshold.\n\nDo not take any painkiller without asking a doctor or pharmacist, as some are not preferred in the first days after a head injury. Return to training follows a staged plan with medical clearance, not simply because the headache has gone.'
  },
  {
    specialty: 'sports_medicine',
    category: 'education',
    title: 'التمرين في صيف مصر — التأقلم على الحرارة',
    titleEn: 'Training through the Egyptian summer — heat acclimatisation',
    body: 'الجسم محتاج حوالي 10-14 يوم عشان يتأقلم على التمرين في الحر: العرق بيبدأ بدري وبيزيد، ونبض القلب بيبقى أقل عند نفس المجهود. عشان كده أول أسبوعين في الصيف (أو بعد ما ترجع من إجازة أو مرض) قلّل مدة وشدة التمرين في الجو الحار وزوّدهم تدريجيًا، واختار أوقات الصبح بدري أو بعد المغرب، وخلي بالك إن الرطوبة العالية (زي السواحل) بتصعّب تبريد الجسم حتى لو الحرارة مش عالية أوي.\n\nفيه ناس خطرها أعلى: الأطفال، كبار السن، أصحاب الوزن الزايد، اللي لياقتهم ضعيفة، اللي لسه خارجين من دور برد أو إسهال أو سخونية، واللي بياخدوا أدوية زي مدرات البول أو بعض أدوية الحساسية أو المنشطات. في رمضان، التمرين العنيف قبل الفطار في الحر مش فكرة كويسة — الأفضل بعد الفطار بوقت كافي.\n\nلو حد وقع أو اتلخبط أو بقى بيتكلم كلام غريب أثناء التمرين في الحر: ده طوارئ. اطلب الإسعاف فورًا وابدأ التبريد في نفس اللحظة (ضل، مية ساقعة على الجسم كله، فوط مبلولة بتلج)، ومتحاولش تشرّبه لو مش واعي كويس.',
    bodyEn: 'The body needs roughly 10–14 days to acclimatise to training in the heat: sweating starts earlier and increases, and heart rate is lower at the same effort. So for the first two weeks of summer (or after returning from holiday or illness) reduce the duration and intensity of sessions in hot conditions and build them up gradually, train early in the morning or after sunset, and remember that high humidity (as on the coast) makes cooling harder even when the temperature is not extreme.\n\nSome people are at higher risk: children, older adults, people with obesity, people with low fitness, anyone just recovering from a cold, diarrhoea or fever, and those taking medicines such as diuretics, some antihistamines or stimulants. During Ramadan, hard training before iftar in the heat is not a good idea — it is better to train a sufficient time after breaking the fast.\n\nIf someone collapses, becomes confused or starts talking strangely while training in the heat, it is an emergency. Call an ambulance immediately and start cooling at once (shade, cold water over the whole body, towels soaked in iced water), and do not try to give fluids to someone who is not fully alert.'
  },
  {
    specialty: 'sports_medicine',
    category: 'redflag',
    title: 'ألم الصدر أثناء التمرين — وقّف واطلب مساعدة',
    titleEn: 'Chest pain during exercise — stop and get help',
    body: 'ألم أو ضغط أو تقل في الصدر أثناء المجهود مش حاجة "تكمّل عليها" أبدًا، حتى لو الشخص رياضي وصغير في السن. وقّف التمرين فورًا لو ظهر أي من دول: ألم أو ضغط في الصدر ممكن يمتد للدراع أو الفك أو الضهر، ضيق نفس مش متناسب مع المجهود، دقات قلب سريعة جدًا أو غير منتظمة، دوخة شديدة أو إغماء، أو عرق بارد وغثيان.\n\nلو الأعراض مستمرة أو شديدة: اطلب الإسعاف فورًا (123 في مصر)، خلّي الشخص يقعد ومتسيبوش لوحده. لو فقد الوعي ومبيتنفسش طبيعي، ابدأ إنعاش قلبي رئوي واستخدم جهاز الصدمات الكهربائية (AED) لو موجود — وده سبب إن كل جيم أو نادي المفروض يكون عنده جهاز وحد متدرب عليه.\n\nالإغماء أثناء التمرين نفسه (مش بعده) علامة خطر محتاجة تقييم قلب قبل أي رجوع للرياضة. وكمان لازم يتقال للطبيب لو فيه تاريخ عائلي لوفاة مفاجئة قبل سن 50 أو مرض قلب وراثي. قرار الرجوع للتمرين بعد أي عرض من دول بيكون للطبيب بس.',
    bodyEn: 'Chest pain, pressure or heaviness during exertion is never something to "push through", even in a young, fit athlete. Stop exercising immediately if any of these appear: chest pain or pressure that may spread to the arm, jaw or back, breathlessness out of proportion to the effort, a very fast or irregular heartbeat, severe dizziness or fainting, or a cold sweat with nausea.\n\nIf symptoms persist or are severe, call an ambulance immediately (123 in Egypt), sit the person down and do not leave them alone. If they lose consciousness and are not breathing normally, start CPR and use an automated external defibrillator (AED) if one is available — which is why every gym or club should have one and someone trained to use it.\n\nFainting during exercise itself (not after it) is a red flag that needs a cardiac assessment before any return to sport. A family history of sudden death before age 50 or of an inherited heart condition must also be reported to the doctor. The decision to return to training after any of these symptoms belongs to the doctor alone.'
  },
  {
    specialty: 'sports_medicine',
    category: 'education',
    title: 'أتمرن ولا أرتاح وأنا عندي برد؟ قاعدة "فوق الرقبة"',
    titleEn: 'Train or rest with a cold? The "above the neck" rule',
    body: 'فيه قاعدة عملية بيستخدمها كتير من أطباء الطب الرياضي: لو الأعراض كلها "فوق الرقبة" بس (رشح، عطس، زور خفيف) ومفيش سخونية، ممكن تتمرن تمرين خفيف لمتوسط وتقلّل الشدة، ولو حسيت إنك أسوأ وقّف. لو فيه أعراض "تحت الرقبة" (كحة من الصدر، تكسير في الجسم، إسهال أو قيء) أو أي سخونية — ارتاح.\n\nالتمرين العنيف وانت عندك سخونية أو عدوى فيروسية عامة ممكن يزوّد خطر التهاب عضلة القلب في حالات نادرة لكن خطيرة، وده سبب إن القاعدة دي مش مجرد نصيحة للراحة. ولو ظهر ألم صدر أو خفقان أو ضيق نفس غير معتاد أو إغماء أثناء أو بعد عدوى، لازم تقييم طبي قبل الرجوع.\n\nبعد ما السخونية تروح والأعراض تتحسن، ارجع بالتدريج على كام يوم بدل ما ترجع لنفس الحمل مرة واحدة. ولو الأعراض طولت أكتر من أسبوع أو اتنين أو بتتكرر كتير، استشير الطبيب.',
    bodyEn: 'Many sports medicine doctors use a practical rule: if all symptoms are "above the neck" only (runny nose, sneezing, a mild sore throat) and there is no fever, light-to-moderate exercise at reduced intensity is usually acceptable — and stop if you feel worse. If there are "below the neck" symptoms (chesty cough, body aches, diarrhoea or vomiting) or any fever, rest.\n\nHard exercise during a fever or a generalised viral infection can, rarely but seriously, increase the risk of inflammation of the heart muscle (myocarditis), which is why this rule is more than comfort advice. If chest pain, palpitations, unusual breathlessness or fainting appear during or after an infection, a medical assessment is needed before returning.\n\nOnce the fever has gone and symptoms are improving, build back up over several days rather than jumping straight back to your usual load. If symptoms last more than a week or two, or keep coming back, consult your doctor.'
  },
  {
    specialty: 'sports_medicine',
    category: 'condition',
    title: 'انقطاع أو اضطراب الدورة عند الرياضيات — مش علامة إنك بتتمرني صح',
    titleEn: 'Missed or irregular periods in female athletes — not a sign of good training',
    body: 'فيه اعتقاد منتشر إن انقطاع الدورة عند الرياضية "طبيعي" أو دليل إنها بتتمرن جامد. الحقيقة إن غياب الدورة 3 شهور أو أكتر (أو عدم نزولها لحد سن 15) عند رياضية كانت منتظمة غالبًا علامة إن الجسم مش واخد طاقة كفاية من الأكل مقارنة بالمجهود — وده اللي كان بيتسمى "ثالوث الرياضية" (نقص الطاقة، اضطراب الدورة، ضعف العظام) وبقى جزء من مفهوم نقص الطاقة النسبي (RED-S) الموجود في المكتبة.\n\nالمشكلة مش في الدورة بس: انخفاض الهرمونات بيأثر على كثافة العظام وبيزوّد خطر كسور الإجهاد، وممكن يأثر على المزاج والأداء والمناعة. علامات تانية تستاهل الانتباه: كسور إجهاد متكررة، إرهاق مستمر، نزول وزن غير مقصود، أو تركيز زايد على الأكل والوزن.\n\nأي تغيير في انتظام الدورة محتاج كشف عند طبيب (طب رياضي أو نسا) لأن له أسباب تانية كتير لازم تتستبعد، وممكن يحتاج أخصائي تغذية وأحيانًا أخصائي نفسي. ومتاخديش هرمونات أو أدوية لتنظيم الدورة من غير تقييم، لأنها ممكن تخبّي المشكلة الأساسية من غير ما تعالجها.',
    bodyEn: 'There is a widespread belief that losing periods is "normal" for an athlete or even proof of hard training. In reality, no period for 3 months or more (or no first period by age 15) in a previously regular athlete is often a sign that the body is not getting enough energy from food relative to training — what used to be called the "female athlete triad" (low energy, menstrual disturbance, weak bones), now part of the broader Relative Energy Deficiency in Sport (RED-S) concept covered in this library.\n\nThe problem is not only the period itself: low hormone levels affect bone density and raise the risk of stress fractures, and can affect mood, performance and immunity. Other signs worth noticing: repeated stress fractures, persistent fatigue, unintended weight loss, or a growing preoccupation with food and weight.\n\nAny change in menstrual regularity needs assessment by a doctor (sports medicine or gynaecology), because there are many other causes that must be ruled out, and it may need a nutrition specialist and sometimes a psychologist. Do not start hormones or cycle-regulating medicines without an assessment, as they can mask the underlying problem without treating it.'
  },
  {
    specialty: 'sports_medicine',
    category: 'education',
    title: 'الجفاف والأملاح — تشرب قد إيه؟',
    titleEn: 'Dehydration and electrolytes — how much should you drink?',
    body: 'الهدف إنك تبدأ التمرين وجسمك مترطّب كويس، وتعوّض اللي بتفقده من غير ما تبالغ. طريقة بسيطة: وزن نفسك قبل وبعد تمرين طويل — الفرق تقريبًا هو المية اللي خسرتها، ولون البول الفاتح (زي عصير الليمون) علامة عامة على ترطيب كويس. علامات الجفاف: عطش شديد، بول غامق وقليل، صداع، دوخة، تقلصات عضلية، وهبوط في الأداء.\n\nفي التمارين الطويلة (أكتر من ساعة تقريبًا) أو في الحر أو مع عرق كتير، الأملاح (خصوصًا الصوديوم) بتبقى مهمة زي المية. لكن كمان الإفراط في شرب المية العادية في السباقات الطويلة ممكن يسبب نقص حاد في الصوديوم في الدم — وده خطير: صداع، غثيان، تورّم، تلخبط، وممكن تشنجات. القاعدة: اشرب حسب العطش وخطة مدروسة، مش "كل ما تقدر".\n\nأي حد عنده مرض في الكلى أو القلب أو بياخد مدرات بول أو ماشي على نظام مية محدد من الطبيب، لازم يسأل طبيبه عن كمية السوائل والأملاح المناسبة ليه، وميعتمدش على النصايح العامة. والتلخبط أو الإغماء أثناء أو بعد مجهود طويل = طوارئ.',
    bodyEn: 'The aim is to start training well hydrated and to replace what you lose without overdoing it. A simple method: weigh yourself before and after a long session — the difference is roughly the water you lost — and pale urine (like lemonade) is a general sign of good hydration. Signs of dehydration: intense thirst, dark and scanty urine, headache, dizziness, muscle cramps and a drop in performance.\n\nIn long sessions (roughly over an hour), in the heat or with heavy sweating, electrolytes (especially sodium) become as important as water. At the same time, drinking excessive plain water during long events can cause a dangerous drop in blood sodium (exercise-associated hyponatraemia): headache, nausea, swelling, confusion and even seizures. The rule: drink to thirst and to a planned strategy, not "as much as you can".\n\nAnyone with kidney or heart disease, taking diuretics, or on a fluid limit set by their doctor must ask their doctor about the right amount of fluids and salt for them rather than relying on general advice. Confusion or collapse during or after prolonged exertion is an emergency.'
  },
  {
    specialty: 'sports_medicine',
    category: 'protocol',
    title: 'الرجوع للتمرين بعد كوفيد-19',
    titleEn: 'Returning to exercise after COVID-19',
    body: 'بعد الإصابة الخفيفة، الشائع إن الرجوع يبدأ بعد ما الأعراض تروح تمامًا بكام يوم، وبشكل تدريجي: أيام من النشاط الخفيف جدًا (مشي، حركة)، بعدين تمرين خفيف قصير، بعدين زيادة تدريجية في المدة ثم الشدة، مع الرجوع خطوة لورا لو الأعراض رجعت أو الإرهاق زاد بوضوح في اليوم اللي بعده.\n\nوقّف واستشير طبيب قبل ما تكمّل لو ظهر: ألم في الصدر، خفقان أو دقات غير منتظمة، ضيق نفس مش متناسب مع المجهود، دوخة أو إغماء — الأعراض دي ممكن تكون مرتبطة بالقلب ومحتاجة تقييم قبل أي تمرين. واللي دخل مستشفى أو كانت إصابته متوسطة أو شديدة، أو عنده مرض مزمن، محتاج موافقة طبية قبل الرجوع أصلًا.\n\nلو فيه أعراض مستمرة بعد أسابيع (كوفيد طويل الأمد)، خصوصًا إرهاق شديد بيزيد بعد أي مجهود ولو بسيط، فالبرنامج التدريجي المعتاد ممكن يضر، والمحتاج هو تنظيم المجهود بإشراف طبي. الرجوع بيتقاس باستجابة الجسم، مش بعدد الأيام.',
    bodyEn: 'After a mild infection, return usually begins a few days after symptoms have fully resolved, and progresses gradually: days of very light activity (walking, mobility), then short, light sessions, then a gradual increase in duration and then intensity — stepping back if symptoms return or fatigue is clearly worse the next day.\n\nStop and consult a doctor before continuing if you notice chest pain, palpitations or an irregular heartbeat, breathlessness out of proportion to effort, dizziness or fainting — these may be heart-related and need assessment before any exercise. Anyone who was hospitalised, had a moderate or severe illness, or has a chronic condition needs medical clearance before starting at all.\n\nIf symptoms persist for weeks (long COVID), especially severe fatigue that worsens after even small efforts (post-exertional malaise), the usual graded programme can be harmful; what is needed is activity pacing under medical supervision. Progress is judged by the body\'s response, not by the number of days.'
  },

  /* ==================== طبيب ==================== */
  {
    specialty: 'doctor',
    category: 'education',
    title: 'التمرين مع السكر — الوقاية من هبوط السكر',
    titleEn: 'Exercising with diabetes — preventing hypoglycaemia',
    body: 'التمرين من أهم أدوات التحكم في السكر، لكن مع الإنسولين أو بعض أقراص السكر (زي مجموعة السلفونيل يوريا) ممكن السكر يهبط أثناء التمرين أو بعده بساعات — وأحيانًا بالليل في نفس اليوم. عشان كده: قيس السكر قبل التمرين (وأثناءه وبعده في التمارين الطويلة أو الجديدة)، وخلي معاك دايمًا مصدر سكر سريع (عصير أو أقراص جلوكوز)، وبلّغ المدرب إنك مريض سكر.\n\nأعراض الهبوط: رعشة، عرق، جوع مفاجئ، خفقان، دوخة، زغللة، تلخبط أو عصبية. لو ظهرت: وقّف فورًا وخد السكر السريع حسب الخطة المتفق عليها مع طبيبك، وقيس تاني بعد حوالي 15 دقيقة، ومترجعش للتمرين في نفس اليوم إلا لو الطبيب قال غير كده. لو الشخص مش قادر يبلع أو فقد الوعي: متحطش حاجة في بقه واطلب الإسعاف فورًا.\n\nمرضى النوع الأول: لو السكر عالي جدًا ومعاه كيتونات في البول أو الدم، التمرين ممنوع لحد ما يتظبط. تعديل جرعات الإنسولين أو الأكل حوالين التمرين قرار طبيب السكر بس — متغيرش أي جرعة من نفسك. وقدّم لطبيبك فكرة عن نوع ومواعيد تمرينك عشان يظبط الخطة معاك.',
    bodyEn: 'Exercise is one of the most important tools for managing blood glucose, but with insulin or some diabetes tablets (such as sulfonylureas) glucose can fall during exercise or hours afterwards — sometimes overnight on the same day. So: check your glucose before exercise (and during and after long or new sessions), always carry a fast-acting sugar source (juice or glucose tablets), and let your coach know you have diabetes.\n\nSymptoms of a low: shaking, sweating, sudden hunger, palpitations, dizziness, blurred vision, confusion or irritability. If they appear, stop immediately, take fast-acting sugar according to the plan agreed with your doctor, recheck after about 15 minutes, and do not return to training that day unless your doctor has advised otherwise. If the person cannot swallow or loses consciousness, put nothing in their mouth and call an ambulance immediately.\n\nFor type 1 diabetes: if glucose is very high with ketones in the urine or blood, exercise must wait until it is controlled. Adjusting insulin doses or food around exercise is a decision for the diabetes doctor only — never change a dose on your own. Share the type and timing of your training with your doctor so the plan can be set with you.'
  },
  {
    specialty: 'doctor',
    category: 'education',
    title: 'التمرين وارتفاع ضغط الدم',
    titleEn: 'Exercise and high blood pressure',
    body: 'التمرين المنتظم (زي المشي السريع أو العجلة أو السباحة، مع تمارين مقاومة معتدلة) بيساعد فعلًا في خفض ضغط الدم، وغالبًا بيكون جزء أساسي من الخطة العلاجية جنب الأدوية مش بديل عنها. المهم تبدأ بالتدريج، وتقيس ضغطك بانتظام، وتبلغ المدرب بالأدوية اللي بتاخدها.\n\nنصايح عملية: متكتمش نفسك وانت بتشيل (اتنفس مع كل تكرار)، تجنّب الأوزان التقيلة جدًا اللي بتخليك تزق بكل قوتك، اعمل تهدئة تدريجية في آخر التمرين بدل ما توقف فجأة (خصوصًا مع أدوية الضغط اللي ممكن تعمل دوخة بعد التمرين)، ولو بتاخد حاصرات بيتا فنبض القلب مش هيعلى زي الطبيعي — استخدم الإحساس بالمجهود بدل النبض.\n\nمتتمرنش لو قراية الضغط وانت مرتاح عالية جدًا (في حدود 180/110 أو أكتر) واتصل بطبيبك. ووقّف التمرين فورًا واطلب مساعدة لو حصل صداع شديد مفاجئ، ألم صدر، زغللة، دوخة شديدة، أو ضعف في ناحية من الجسم. أي حد ضغطه مش متظبط أو عنده مرض قلب أو كلى محتاج موافقة طبية قبل ما يبدأ برنامج جديد.',
    bodyEn: 'Regular exercise (such as brisk walking, cycling or swimming, plus moderate resistance training) genuinely helps lower blood pressure and is usually a core part of the treatment plan alongside medication, not a replacement for it. Start gradually, measure your blood pressure regularly, and tell your coach which medicines you take.\n\nPractical tips: do not hold your breath while lifting (breathe with every repetition), avoid very heavy loads that make you strain maximally, cool down gradually at the end rather than stopping suddenly (especially with blood pressure medicines that can cause dizziness after exercise), and if you take a beta-blocker your heart rate will not rise normally — use perceived effort instead of heart rate.\n\nDo not exercise if your resting reading is very high (around 180/110 or above) — contact your doctor. Stop immediately and get help if you develop a sudden severe headache, chest pain, blurred vision, severe dizziness or weakness on one side of the body. Anyone whose blood pressure is not controlled, or who has heart or kidney disease, needs medical clearance before starting a new programme.'
  },
  {
    specialty: 'doctor',
    category: 'education',
    title: 'التمرين أثناء الحمل — مبادئ عامة',
    titleEn: 'Exercise during pregnancy — general principles',
    body: 'في الحمل الطبيعي غير المعقّد، النشاط البدني المعتدل مفيد للأم وآمن عمومًا — بيساعد في التحكم في الوزن وسكر الحمل وتحسين المزاج والنوم. الإرشادات الشائعة بتنصح بحوالي 150 دقيقة في الأسبوع من نشاط معتدل (تقدري تتكلمي وانتي بتتمرني)، زي المشي والسباحة والعجلة الثابتة وتمارين المقاومة الخفيفة — لكن ده كله بعد موافقة طبيب النسا المتابع، لأن فيه حالات التمرين فيها ممنوع أو محتاج تعديل.\n\nتجنبي: الرياضات اللي فيها احتكاك أو خطر وقوع أو خبط في البطن، الغطس، التمرين في حر شديد أو "اليوجا الساخنة"، ومن بعد الشهور الأولى تجنبي النوم على ضهرك فترات طويلة أثناء التمرين. الحمل مش وقت تكسري فيه أرقام قياسية أو تبدأي رياضة عنيفة جديدة.\n\nوقّفي التمرين وكلّمي طبيبك فورًا لو حصل: نزيف مهبلي، نزول مية، انقباضات منتظمة ومؤلمة، ضيق نفس قبل المجهود، دوخة أو إغماء، صداع شديد، ألم صدر، ضعف عضلي بيأثر على التوازن، أو ألم وتورّم في سمانة الرجل. وبعد الولادة، الرجوع للتمرين (وخصوصًا تمارين البطن والقفز) بيكون بالتدريج وبعد الكشف.',
    bodyEn: 'In a normal, uncomplicated pregnancy, moderate physical activity benefits the mother and is generally safe — it helps with weight control, gestational diabetes, mood and sleep. Common guidance suggests about 150 minutes a week of moderate activity (you can still talk while exercising), such as walking, swimming, stationary cycling and light resistance training — but only after approval from the obstetrician following the pregnancy, because in some conditions exercise is not allowed or needs modification.\n\nAvoid contact sports or activities with a risk of falls or blows to the abdomen, scuba diving, exercising in extreme heat or "hot yoga", and after the early months avoid lying flat on your back for long periods during exercise. Pregnancy is not the time for personal records or for starting a new high-intensity sport.\n\nStop exercising and contact your doctor immediately if you experience vaginal bleeding, leaking fluid, regular painful contractions, breathlessness before exertion, dizziness or fainting, severe headache, chest pain, muscle weakness affecting balance, or calf pain or swelling. After delivery, return to exercise (especially abdominal work and jumping) should be gradual and follow a check-up.'
  },
  {
    specialty: 'doctor',
    category: 'condition',
    title: 'نقص الحديد عند الرياضيين',
    titleEn: 'Iron deficiency in athletes',
    body: 'نقص الحديد من أشهر أسباب الإرهاق وهبوط الأداء عند الرياضيين، وممكن يكون موجود حتى قبل ما يوصل لأنيميا واضحة (مخزون الحديد قليل والهيموجلوبين لسه طبيعي). الأكثر عرضة: الرياضيات خصوصًا مع دورة غزيرة، عدّائي المسافات الطويلة، النباتيين، المراهقين في فترة النمو، واللي بيقللوا أكلهم عشان الوزن.\n\nالأعراض ممكن تكون عامة: تعب مستمر، ضيق نفس مع مجهود كان سهل، نبض أسرع من المعتاد، صداع، ضعف تركيز، أو برد في الأطراف. التشخيص بيكون بتحاليل دم بيطلبها الطبيب (زي صورة الدم ومخزون الحديد "الفيريتين")، مش بالأعراض لوحدها.\n\nمتاخدش حديد "احتياطي" من غير تحليل: الحديد الزيادة ممكن يضر، وفيه أنواع أنيميا وراثية (زي أنيميا البحر المتوسط، وهي شائعة في مصر) الحديد مش علاجها وممكن يأذي. الطبيب هو اللي يحدد لو محتاج مكمل وقد إيه ولمدة قد إيه، ويدوّر على السبب (زي نزيف أو مشكلة امتصاص). نصيحة أكل عامة: الشاي مع الوجبة بيقلل امتصاص الحديد، فالأفضل يتأخر ساعة أو اتنين بعد الأكل.',
    bodyEn: 'Iron deficiency is one of the most common causes of fatigue and falling performance in athletes, and it can be present even before it becomes obvious anaemia (low iron stores with haemoglobin still normal). Those most at risk: female athletes, especially with heavy periods, distance runners, vegetarians, adolescents during growth spurts, and anyone restricting food to control weight.\n\nSymptoms can be vague: persistent tiredness, breathlessness with efforts that used to be easy, a faster-than-usual heart rate, headaches, poor concentration or cold hands and feet. Diagnosis is by blood tests ordered by a doctor (such as a full blood count and ferritin for iron stores), not by symptoms alone.\n\nDo not take iron "just in case" without testing: excess iron can be harmful, and some inherited anaemias (such as thalassaemia trait, which is common in Egypt) are not treated with iron and can be made worse by it. The doctor decides whether a supplement is needed, how much and for how long, and looks for the cause (such as blood loss or poor absorption). A general food tip: tea with meals reduces iron absorption, so it is better to have it an hour or two after eating.'
  },
  {
    specialty: 'doctor',
    category: 'condition',
    title: 'الربو والتمرين',
    titleEn: 'Asthma and exercise',
    body: 'أغلب اللي عندهم ربو متظبط يقدروا يتمرنوا ويتنافسوا في أعلى المستويات. بعض الناس بيحصل عندهم ضيق في الشعب الهوائية بسبب المجهود نفسه: كحة أو صفير أو كتمة أو ضيق نفس أثناء التمرين أو بعده بدقايق، وبيزيد مع الهوا البارد أو الناشف أو التراب والتلوث.\n\nحاجات بتساعد: إحماء تدريجي كويس، تجنّب التمرين في الأماكن المتربة أو وقت التلوث العالي، والالتزام بالخطة اللي حددها الطبيب (أحيانًا بخاخ قبل التمرين). البخاخ الموسّع لازم يكون معاك في كل تمرين، والمدرب لازم يعرف مكانه. ولو الأعراض بتظهر كتير، ده معناه إن الربو محتاج مراجعة مع الطبيب مش إنك تبطّل رياضة.\n\nطوارئ: لو البخاخ مش بيجيب نتيجة، أو الشخص مش قادر يكمل جملة، أو شفايفه زرقا، أو بيتعب بسرعة وبيتلخبط — اطلب الإسعاف فورًا. وكمان مش كل ضيق نفس مع التمرين يبقى ربو (فيه أسباب في القلب أو الحنجرة أو قلة اللياقة)، عشان كده التشخيص بيكون بالكشف واختبارات التنفس.',
    bodyEn: 'Most people with well-controlled asthma can train and compete at the highest levels. Some people experience narrowing of the airways triggered by exercise itself: cough, wheeze, chest tightness or breathlessness during or a few minutes after exercise, made worse by cold or dry air, dust and pollution.\n\nWhat helps: a good gradual warm-up, avoiding dusty places or high-pollution times, and sticking to the plan set by the doctor (sometimes an inhaler before exercise). Your reliever inhaler should be with you at every session, and your coach should know where it is. If symptoms happen often, it means the asthma needs reviewing with the doctor — not that you should give up sport.\n\nEmergency: if the reliever is not working, the person cannot finish a sentence, their lips turn blue, or they tire quickly and become confused, call an ambulance immediately. Also, not all breathlessness during exercise is asthma (there are heart, throat/vocal cord and fitness-related causes), which is why diagnosis relies on examination and breathing tests.'
  },
  {
    specialty: 'doctor',
    category: 'condition',
    title: 'الأنيميا (فقر الدم) — أساسيات',
    titleEn: 'Anaemia — the basics',
    body: 'الأنيميا معناها إن نسبة الهيموجلوبين في الدم أقل من الطبيعي، فالدم بيوصّل أكسجين أقل للعضلات والأعضاء. ليها أسباب كتير: نقص الحديد (الأشهر)، نقص فيتامين ب12 أو حمض الفوليك، فقدان دم (دورة غزيرة أو نزيف من الجهاز الهضمي)، أمراض مزمنة، أو أسباب وراثية زي أنيميا البحر المتوسط والأنيميا المنجلية.\n\nالأعراض الشائعة: تعب وإرهاق، شحوب، نهجان مع مجهود بسيط، دوخة، صداع، وخفقان. لكن الأعراض لوحدها مش كفاية للتشخيص — لازم تحليل دم، والأهم إن الطبيب يعرف السبب، لأن علاج كل نوع مختلف تمامًا، وأخد مكملات عشوائية ممكن يخبّي سبب مهم أو يضر.\n\nعلامات تستدعي كشف سريع: براز أسود أو فيه دم، نزيف غزير، إغماء، نهجان وانت مرتاح، ألم صدر، أو نزول وزن غير مبرر. وبالنسبة للتمرين: الشخص اللي عنده أنيميا واضحة محتاج رأي الطبيب في شدة التمرين المناسبة لحد ما تتعالج، وبيتقدم تدريجيًا مع تحسن التحاليل.',
    bodyEn: 'Anaemia means the haemoglobin level in the blood is lower than normal, so the blood carries less oxygen to muscles and organs. It has many causes: iron deficiency (the most common), low vitamin B12 or folate, blood loss (heavy periods or bleeding from the gut), chronic diseases, or inherited causes such as thalassaemia and sickle cell disease.\n\nCommon symptoms: tiredness and fatigue, pallor, breathlessness with little effort, dizziness, headaches and palpitations. But symptoms alone are not enough for a diagnosis — a blood test is needed, and above all the doctor needs to find the cause, because each type is treated very differently, and taking random supplements can hide an important cause or cause harm.\n\nSigns that need a prompt medical visit: black or bloody stools, heavy bleeding, fainting, breathlessness at rest, chest pain, or unexplained weight loss. Regarding exercise: someone with significant anaemia needs the doctor\'s view on appropriate training intensity until it is treated, progressing gradually as blood results improve.'
  },
  {
    specialty: 'doctor',
    category: 'condition',
    title: 'أمراض الكلى والبروتين — استشير قبل أي نظام عالي البروتين',
    titleEn: 'Kidney disease and protein — ask before any high-protein diet',
    body: 'الأنظمة عالية البروتين ومكملات البروتين آمنة عمومًا لأغلب الأصحاء، لكن الوضع مختلف مع أمراض الكلى المزمنة: الكلى الضعيفة ممكن تتأثر بكميات البروتين العالية، ومرضى الكلى غالبًا بيحتاجوا كمية بروتين وأملاح وسوائل محددة بدقة من الطبيب وأخصائي التغذية. والمشكلة إن كتير من الناس عندهم ضعف في وظائف الكلى ومش عارفين، خصوصًا مرضى السكر والضغط وكبار السن واللي في عيلتهم أمراض كلى.\n\nعشان كده: لو عندك أي مرض كلى أو من الفئات دي، اعمل تحاليل وظائف الكلى واستشير طبيبك قبل ما تبدأ نظام عالي البروتين أو مكملات زي الكرياتين. وبلّغ الطبيب دايمًا لو بتاخد كرياتين لأنه ممكن يرفع قراية "الكرياتينين" في التحليل ويلخبط التفسير.\n\nحاجات بتأذي الكلى عند الرياضيين: الجفاف الشديد، الاستخدام المتكرر للمسكنات المضادة للالتهاب، والمكملات مجهولة المصدر. علامات تستدعي الكشف: تورّم في الرجلين أو الوش، تغيّر في كمية البول أو لونه (خصوصًا بول غامق زي الكولا بعد مجهود عنيف — ده طوارئ)، أو ارتفاع ضغط جديد. الحالات دي بتتحوّل لطبيب الكلى وأخصائي التغذية، مش بتتظبط بنصايح عامة.',
    bodyEn: 'High-protein diets and protein supplements are generally safe for most healthy people, but chronic kidney disease is different: weakened kidneys can be affected by high protein intakes, and people with kidney disease often need protein, salt and fluid amounts set precisely by their doctor and a dietitian. The catch is that many people have reduced kidney function without knowing it, especially those with diabetes or high blood pressure, older adults, and people with a family history of kidney disease.\n\nSo if you have any kidney condition or belong to these groups, get kidney function tests and consult your doctor before starting a high-protein diet or supplements such as creatine. Always tell your doctor if you take creatine, as it can raise the "creatinine" value on blood tests and confuse interpretation.\n\nThings that harm the kidneys in athletes: severe dehydration, repeated use of anti-inflammatory painkillers, and supplements of unknown origin. Signs that need a medical visit: swelling of the legs or face, a change in urine amount or colour (especially cola-coloured urine after very hard exertion — this is an emergency), or new high blood pressure. These cases are referred to a nephrologist and a dietitian, not managed with general advice.'
  },

  /* ==================== صيدلي ==================== */
  {
    specialty: 'pharmacist',
    category: 'medication',
    title: 'أدوية بتغيّر استجابة جسمك للتمرين — حاصرات بيتا والإنسولين ومدرات البول',
    titleEn: 'Medicines that change your response to exercise — beta-blockers, insulin and diuretics',
    body: 'حاصرات بيتا (من أدوية الضغط والقلب) بتقلل نبض القلب وبتمنعه يعلى زي الطبيعي مع المجهود، فمناطق النبض المعتادة في التمرين مش هتنفع — الأفضل الاعتماد على الإحساس بالمجهود أو اختبار الكلام. ممكن كمان تحس إن قدرتك على المجهود العالي أقل، ولو عندك سكر فممكن تخبّي بعض أعراض هبوط السكر زي الخفقان.\n\nالإنسولين وبعض أقراص السكر ممكن تسبب هبوط سكر أثناء أو بعد التمرين بساعات. تعديل الجرعة أو ميعادها حوالين التمرين قرار الطبيب، والمهم تقيس السكر، وتخلي معاك سكر سريع، وتعرف إن الحقن في عضلة هتشتغل عليها جامد ممكن يغيّر سرعة امتصاص الإنسولين. مدرات البول بتزوّد فقد المية والأملاح (زي البوتاسيوم والصوديوم)، فبتزوّد خطر الجفاف والتقلصات والإجهاد الحراري، خصوصًا في الصيف.\n\nالقاعدة الذهبية: متوقفش ولا تغيّر جرعة أي دواء بسبب التمرين من غير ما ترجع للطبيب اللي كاتبه. وبلّغ المدرب والصيدلي بكل أدويتك (حتى أدوية البرد والحساسية المنومة، وأدوية الكوليسترول لو حسيت بألم عضلي غير معتاد) عشان البرنامج يتصمم حواليها بأمان.',
    bodyEn: 'Beta-blockers (used for blood pressure and heart conditions) lower heart rate and stop it rising normally with effort, so the usual training heart-rate zones will not work — perceived exertion or the "talk test" is a better guide. You may also find high-intensity work harder, and in people with diabetes they can hide some warning signs of a low, such as palpitations.\n\nInsulin and some diabetes tablets can cause hypoglycaemia during exercise or hours afterwards. Adjusting the dose or timing around exercise is the doctor\'s decision; what matters is checking your glucose, carrying fast-acting sugar, and knowing that injecting into a muscle you are about to work hard can change how fast insulin is absorbed. Diuretics increase the loss of water and salts (such as potassium and sodium), raising the risk of dehydration, cramps and heat illness, especially in summer.\n\nThe golden rule: never stop or change the dose of any medicine because of training without going back to the doctor who prescribed it. Tell your coach and pharmacist about all your medicines (including sedating cold and allergy remedies, and cholesterol medicines if you notice unusual muscle pain) so the programme can be designed safely around them.'
  },
  {
    specialty: 'pharmacist',
    category: 'medication',
    title: 'مين لازم يسأل قبل ما ياخد مسكنات مضادة للالتهاب (NSAIDs)؟',
    titleEn: 'Who should check before taking anti-inflammatory painkillers (NSAIDs)?',
    body: 'المقالة دي مكمّلة لمقالة المسكنات في المكتبة، وبتركز على مين الأمان بالنسبة له أقل. اسأل الطبيب أو الصيدلي الأول لو: عندك تاريخ قرحة أو نزيف في المعدة، مرض في الكلى، ضغط عالي أو مرض قلب، ربو بيزيد مع الأسبرين أو المسكنات، بتاخد أدوية سيولة أو كورتيزون أو بعض أدوية الاكتئاب أو أدوية ضغط معينة، حامل (خصوصًا في النص التاني من الحمل)، أو كبير في السن.\n\nأخطاء شائعة عند الرياضيين: أخد مسكن قبل ماتش أو سباق طويل "عشان متحسش بالألم" — ده بيخبي إشارة الإصابة، ومع الجفاف والمجهود الطويل بيزوّد خطر إصابة الكلى. كمان الجمع بين نوعين مضادين للالتهاب في نفس الوقت (زي قرص مع فوار أو مع دوا برد فيه نفس المادة)، والاستمرار عليها أسابيع من غير متابعة.\n\nفيه بدائل ممكن الصيدلي يقترحها حسب حالتك، زي المسكنات اللي مش مضادة للالتهاب أو المستحضرات الموضعية على الجلد (امتصاصها في الجسم أقل لكن برضه ليها احتياطات). ولو الألم محتاج مسكن أكتر من كام يوم، فده سبب للكشف مش لزيادة المسكن. أوقف الدوا واطلب مساعدة لو حصل براز أسود، قيء دم، ألم معدة شديد، تورّم، أو ضيق نفس.',
    bodyEn: 'This article complements the painkiller article in the library and focuses on who is at higher risk. Ask a doctor or pharmacist first if you have a history of stomach ulcers or bleeding, kidney disease, high blood pressure or heart disease, asthma that worsens with aspirin or painkillers, if you take blood thinners, corticosteroids, some antidepressants or certain blood pressure medicines, if you are pregnant (especially in the second half of pregnancy), or if you are older.\n\nCommon mistakes among athletes: taking a painkiller before a match or a long race "so I do not feel the pain" — it hides the injury signal, and combined with dehydration and prolonged effort it raises the risk of kidney injury. Also combining two anti-inflammatories at once (for example a tablet plus an effervescent, or a cold remedy containing the same ingredient), and staying on them for weeks without follow-up.\n\nThere are alternatives the pharmacist may suggest depending on your situation, such as non-anti-inflammatory painkillers or topical products applied to the skin (less is absorbed into the body, but they still have precautions). If pain needs a painkiller for more than a few days, that is a reason to be examined, not to take more. Stop the medicine and seek help if you notice black stools, vomiting blood, severe stomach pain, swelling, or shortness of breath.'
  },
  {
    specialty: 'pharmacist',
    category: 'supplement',
    title: 'تلوث المكملات والمنشطات — الرياضي مسؤول عن كل حاجة في جسمه',
    titleEn: 'Supplement contamination and doping — athletes are responsible for everything in their body',
    body: 'في قوانين مكافحة المنشطات (WADA والمنظمة المصرية لمكافحة المنشطات)، الرياضي مسؤول عن أي مادة محظورة تتلاقى في عينته، حتى لو كانت جاية من مكمل ملوّث ومكانش يعرف. ودراسات كتير لقت إن نسبة من المكملات — خصوصًا مكملات "حرق الدهون" و"رفع الهرمونات" و"ما قبل التمرين" — فيها منشطات أو هرمونات مش مكتوبة على العلبة، وده غير المنتجات المغشوشة أو المهربة.\n\nعشان تقلل الخطر: اسأل نفسك الأول هل المكمل ده محتاجه فعلًا، واشتري من مصدر موثوق، وفضّل المنتجات اللي عليها شهادة اختبار مستقل للرياضيين (زي Informed Sport أو NSF Certified for Sport) — وده بيقلل الخطر لكن مش بيلغيه. ابعد عن أي منتج بيوعد بنتايج "زي الهرمونات" أو مكتوب عليه مكونات غريبة أو خلطات "مسجلة الملكية" مش واضح فيها الكميات.\n\nولو بتنافس رسميًا وبتاخد دوا لازم لحالة طبية، راجع مع الطبيب والصيدلي هل فيه مادة محظورة وهل محتاج "إعفاء للاستخدام العلاجي" (TUE) قبل المنافسة. وبعيدًا عن المنشطات: المكملات الملوثة ممكن تأذي الكبد أو القلب أو الكلى، فأي أعراض غريبة بعد مكمل جديد (خفقان، اصفرار، بول غامق) = وقّفه واستشير طبيب.',
    bodyEn: 'Under anti-doping rules (WADA and the Egyptian National Anti-Doping Organisation), an athlete is responsible for any prohibited substance found in their sample, even if it came from a contaminated supplement they knew nothing about. Many studies have found that a proportion of supplements — especially "fat burners", "hormone boosters" and "pre-workouts" — contain stimulants or hormones not listed on the label, on top of counterfeit or smuggled products.\n\nTo reduce the risk: first ask whether you really need the supplement, buy from a reliable source, and prefer products carrying independent third-party testing for athletes (such as Informed Sport or NSF Certified for Sport) — this lowers the risk but does not remove it. Avoid any product that promises "steroid-like" results, lists unusual ingredients, or uses "proprietary blends" with no clear amounts.\n\nIf you compete officially and need a medicine for a medical condition, check with your doctor and pharmacist whether it contains a prohibited substance and whether you need a Therapeutic Use Exemption (TUE) before competing. Beyond doping, contaminated supplements can harm the liver, heart or kidneys, so any unusual symptoms after a new supplement (palpitations, yellowing of the skin or eyes, dark urine) mean stop it and see a doctor.'
  },

  /* ==================== طبيب عظام ==================== */
  {
    specialty: 'ortho',
    category: 'condition',
    title: 'هشاشة العظام والتمرين — إيه المفيد وإيه اللي نتجنبه',
    titleEn: 'Osteoporosis and exercise — what helps and what to avoid',
    body: 'التمرين جزء أساسي من التعامل مع هشاشة العظام وقلة كثافتها، مش حاجة نبعد عنها. أكتر حاجات مفيدة: تمارين المقاومة المتدرجة للعضلات الكبيرة، التمارين اللي فيها تحميل وزن (زي المشي، وأحيانًا تمارين تأثير خفيف حسب الحالة)، وتمارين التوازن اللي بتقلل خطر الوقوع — لأن الوقوع هو السبب الأساسي للكسور.\n\nمع الهشاشة الواضحة أو تاريخ كسور، بنتجنب عادة: ثني العمود الفقري لقدام تحت حمل أو بتكرار كتير (زي تمارين البطن التقليدية أو لمس صوابع الرجل مع فرد الركبة)، والالتواء العنيف للجذع، والحركات اللي فيها خطر وقوع. تحديد شدة التمرين المناسبة بيعتمد على نتيجة قياس كثافة العظام (DEXA) وتاريخ الكسور، فالبرنامج لازم يتعمل بعد تقييم طبي ومع أخصائي.\n\nعلامة خطر: ألم مفاجئ في الضهر بعد مجهود بسيط أو كحة أو شيل حاجة خفيفة، أو قِصر ملحوظ في الطول، ممكن يكون كسر انضغاطي في فقرة ومحتاج كشف. والعلاج الدوائي والكالسيوم وفيتامين د قرار الطبيب حسب التحاليل، مش بالاجتهاد الشخصي.',
    bodyEn: 'Exercise is a core part of managing osteoporosis and low bone density, not something to avoid. What helps most: progressive resistance training for the large muscle groups, weight-bearing activity (such as walking, and sometimes light impact exercise depending on the case), and balance training to reduce the risk of falls — because falls are the main cause of fractures.\n\nWith established osteoporosis or a history of fractures, we usually avoid: loaded or highly repetitive forward bending of the spine (such as traditional sit-ups or straight-leg toe touches), forceful twisting of the trunk, and movements with a high risk of falling. The appropriate intensity depends on the bone density scan (DEXA) result and fracture history, so the programme should be designed after a medical assessment and with a specialist.\n\nRed flag: sudden back pain after a minor effort, a cough or lifting something light, or a noticeable loss of height, may be a vertebral compression fracture and needs assessment. Medication, calcium and vitamin D are the doctor\'s decision based on test results, not personal guesswork.'
  },
  {
    specialty: 'ortho',
    category: 'redflag',
    title: 'خلع الكتف — أول خطوات',
    titleEn: 'Shoulder dislocation — the first steps',
    body: 'خلع الكتف بيحصل غالبًا مع وقعة على دراع ممدود أو شد الدراع لورا وهو مرفوع. العلامات: ألم شديد، شكل الكتف متغير (مربّع أو فيه نتوء)، وعدم القدرة على تحريك الدراع. الخطوة الأولى: متحاولش ترجّعه بنفسك أو تخلي حد غير مختص يرجّعه في الملعب — ممكن يكون فيه كسر مصاحب أو إصابة في عصب أو شريان، والترجيع الغلط بيزوّد الضرر.\n\nثبّت الدراع في الوضع المريح للمصاب (ممكن بشنطة أو علاقة أو إن هو يسنده بإيده التانية)، وحط ثلج ملفوف، وروح الطوارئ. قبل وبعد الترجيع بيتعمل فحص للإحساس والنبض في الدراع والإيد، وغالبًا أشعة. لو فيه تنميل أو برودة أو لون الإيد اتغيّر، ده أولوية قصوى.\n\nبعد الترجيع، المتابعة مع طبيب العظام مهمة، لأن خطر تكرار الخلع عالي خصوصًا عند الرياضيين الصغيرين في السن، وأحيانًا بيحتاج رنين أو قرار جراحي. والرجوع للرياضة بيكون بعد برنامج تأهيل يرجّع القوة والثبات، مش بمجرد ما الألم يروح.',
    bodyEn: 'A shoulder dislocation usually happens from a fall on an outstretched arm or the arm being forced backwards while raised. Signs: severe pain, a changed shoulder shape (squared off or with a bulge), and inability to move the arm. First step: do not try to put it back yourself or let anyone who is not qualified do it on the pitch — there may be an associated fracture or a nerve or artery injury, and an incorrect reduction can add damage.\n\nSupport the arm in whatever position is most comfortable for the injured person (a bag strap, a sling, or holding it with the other hand), apply wrapped ice, and go to the emergency department. Sensation and pulses in the arm and hand are checked before and after reduction, and an X-ray is usually taken. Numbness, coldness or a change in the colour of the hand is a top priority.\n\nAfter reduction, orthopaedic follow-up matters, because the risk of repeat dislocation is high, especially in young athletes, and an MRI or a surgical decision is sometimes needed. Return to sport follows a rehab programme that restores strength and stability, not simply the disappearance of pain.'
  },
  {
    specialty: 'ortho',
    category: 'redflag',
    title: 'كسور الإجهاد عالية الخطورة — علامات متستناش عليها',
    titleEn: 'High-risk stress fractures — warning signs you should not wait on',
    body: 'المقالة دي مكمّلة لمقالة كسور الإجهاد عند العدّائين. مش كل كسور الإجهاد زي بعض: فيه أماكن الكسر فيها ممكن يكمل لكسر كامل أو يلتئم بصعوبة، وأشهرها: عنق عظمة الفخذ (ألم في الأُربية أو أعلى الفخذ مع الجري)، الجزء الأمامي من عظمة القصبة، عظمة "النافيكيولار" في منتصف القدم، قاعدة عظمة المشط الخامسة، وعظام تحت إصبع القدم الكبير.\n\nعلامات تستدعي وقف الجري أو القفز فورًا والكشف: ألم موضعي في نقطة معينة على العظمة بيزيد مع كل تمرين، ألم بيحصل حتى في الراحة أو بالليل، ألم مع النط على رجل واحدة، أو عرج. ألم الأُربية عند عدّاء بيزيد مع الجري بالذات محتاج تقييم سريع لأن كسر عنق الفخذ ممكن ينزاح.\n\nالأشعة العادية ممكن تطلع طبيعية في الأسابيع الأولى، فعدم ظهور كسر فيها مش معناه إن مفيش — الطبيب ممكن يطلب رنين. وبرضه لازم يتدوّر على السبب (زيادة مفاجئة في الحمل، نقص طاقة أو كالسيوم أو فيتامين د، اضطراب الدورة) عشان الكسر ميتكررش.',
    bodyEn: 'This article complements the article on stress fractures in runners. Not all stress fractures are equal: in some locations the fracture can progress to a complete break or heal poorly. The best known are the femoral neck (groin or upper thigh pain with running), the front of the tibia, the navicular bone in the midfoot, the base of the fifth metatarsal, and the small bones under the big toe (sesamoids).\n\nSigns that mean stop running or jumping immediately and get assessed: pain localised to one spot on the bone that worsens with each session, pain at rest or at night, pain when hopping on one leg, or a limp. Groin pain in a runner that worsens specifically with running needs prompt assessment, because a femoral neck fracture can displace.\n\nPlain X-rays can look normal in the first weeks, so a normal X-ray does not rule a fracture out — the doctor may request an MRI. The cause must also be looked for (a sudden jump in training load, low energy, calcium or vitamin D, menstrual disturbance) so that the fracture does not recur.'
  },
  {
    specialty: 'ortho',
    category: 'condition',
    title: 'صفائح النمو عند الأطفال والتدريب',
    titleEn: 'Children\'s growth plates and training',
    body: 'صفائح النمو مناطق غضروفية قرب أطراف العظام عند الأطفال والمراهقين، وهي أضعف من الأربطة والأوتار المحيطة بيها. عشان كده الإصابة اللي عند الكبير بتبقى "التواء"، عند الطفل ممكن تكون كسر في صفيحة النمو. تمارين المقاومة للأطفال آمنة ومفيدة لما تكون بإشراف مدرب مؤهل، بتقنية سليمة، وبأوزان مناسبة وتدرج هادي — الخطر الحقيقي من التقنية الغلط وقلة الإشراف، مش من فكرة التمرين نفسها.\n\nفيه مشاكل شائعة في سن النمو مرتبطة بشد الأوتار على نقط اتصالها بالعظم، زي ألم تحت الركبة (أوسجود شلاتر) أو ألم في كعب القدم (سيفر)، وبتزيد مع فترات النمو السريع وكثرة الجري والنط. نصايح عامة: متخصصش الطفل في رياضة واحدة بدري، وخلّي عنده يوم أو اتنين راحة في الأسبوع، وفترات راحة من نفس الرياضة خلال السنة، وخلّي بالك من الزيادة المفاجئة في الحمل وقت فترات الطول السريعة.\n\nروح لطبيب لو فيه: ألم مستمر حوالين مفصل أو في نفس المكان، عرج، ألم بالليل، تورّم أو عدم قدرة على الحركة بعد إصابة قرب مفصل، أو ألم في الورك أو الركبة عند مراهق بيعرج (مشاكل في مفصل الفخذ ممكن تظهر كألم في الركبة). الطفل مش "كبير صغير"، وإصاباته محتاجة تقييم طبيب متخصص.',
    bodyEn: 'Growth plates are areas of cartilage near the ends of bones in children and adolescents, and they are weaker than the surrounding ligaments and tendons. That is why an injury that would be a "sprain" in an adult may be a growth plate fracture in a child. Resistance training for children is safe and beneficial when supervised by a qualified coach, with good technique, appropriate loads and gentle progression — the real risk comes from poor technique and lack of supervision, not from the training itself.\n\nSome common problems during growth relate to tendons pulling on their attachment to bone, such as pain below the knee (Osgood–Schlatter) or heel pain (Sever\'s disease), and they increase during growth spurts and with lots of running and jumping. General advice: avoid early specialisation in a single sport, keep one or two rest days a week and breaks from the same sport during the year, and watch for sudden jumps in load during periods of rapid growth.\n\nSee a doctor if there is persistent pain around a joint or in the same spot, a limp, night pain, swelling or inability to move after an injury near a joint, or hip or knee pain in a limping adolescent (hip problems can show up as knee pain). A child is not a "small adult", and their injuries need assessment by a qualified doctor.'
  },

  /* ==================== طبيب أشعة ==================== */
  {
    specialty: 'radiology',
    category: 'imaging',
    title: 'التواء الكاحل — إمتى محتاج أشعة؟ (قواعد أوتاوا)',
    titleEn: 'Ankle sprain — when is an X-ray needed? (Ottawa ankle rules)',
    body: 'أغلب التواءات الكاحل إصابات أربطة ومش محتاجة أشعة. قواعد أوتاوا أداة بيستخدمها الأطباء عشان يحددوا مين محتاج أشعة عادية لاستبعاد كسر. في الكاحل: الأشعة مطلوبة لو فيه ألم في منطقة الكعبين (عظمة الكاحل البارزة من الناحيتين) ومعاه واحد من دول: ألم عند الضغط على الحافة الخلفية أو طرف عظمة الكاحل الخارجية أو الداخلية، أو عدم القدرة على المشي 4 خطوات لا بعد الإصابة مباشرة ولا وقت الكشف.\n\nفي القدم: الأشعة مطلوبة لو فيه ألم في منتصف القدم ومعاه ألم عند الضغط على قاعدة عظمة المشط الخامسة (الناحية الخارجية من نص القدم) أو على عظمة النافيكيولار (الناحية الداخلية)، أو عدم القدرة على المشي 4 خطوات. الضغط والتقييم ده بيعمله طبيب أو مختص مدرّب، مش الشخص لنفسه.\n\nالقواعد دي متصممة أساسًا للكبار وبتستخدم بحذر مع الأطفال، ومبتنفعش لو فيه تنميل أو إصابات تانية بتشتت الإحساس بالألم أو لو الشخص مش واعي كويس. ولو الأشعة طبيعية والألم أو عدم الثبات استمر أكتر من أسبوع أو اتنين، ممكن يكون فيه إصابة غضروف أو رباط أعلى الكاحل أو كسر مش باين — ارجع للطبيب.',
    bodyEn: 'Most ankle sprains are ligament injuries and do not need an X-ray. The Ottawa ankle rules are a tool doctors use to decide who needs a plain X-ray to rule out a fracture. For the ankle: an X-ray is indicated if there is pain in the malleolar zone (the bony bumps on either side of the ankle) plus any one of: tenderness on the back edge or tip of the outer or inner ankle bone, or inability to walk 4 steps both immediately after the injury and at the time of assessment.\n\nFor the foot: an X-ray is indicated if there is midfoot pain plus tenderness at the base of the fifth metatarsal (outer side of the midfoot) or over the navicular bone (inner side), or inability to walk 4 steps. This palpation and assessment is done by a trained doctor or clinician, not self-applied.\n\nThe rules were designed mainly for adults and are used with caution in children, and they do not apply when there is numbness, other distracting injuries, or reduced alertness. If the X-ray is normal but pain or instability persists beyond a week or two, there may be a cartilage injury, a high ankle sprain or a hidden fracture — go back to your doctor.'
  },

  /* ==================== أخصائي علاج طبيعي ==================== */
  {
    specialty: 'physio',
    category: 'education',
    title: 'خرافات شائعة عن ألم أسفل الضهر',
    titleEn: 'Common myths about low back pain',
    body: 'خرافة: "الراحة في السرير هي العلاج". الحقيقة إن الراحة الطويلة في السرير بتأخر التعافي، والأفضل البقاء في حركة ونشاط في حدود الألم المحتمل. خرافة: "لازم أعمل رنين عشان أعرف السبب". في أغلب الحالات بدون علامات خطر، الأشعة مش بتغير العلاج، وحاجات زي "انتفاخ غضروفي" أو "خشونة" بتظهر كتير جدًا عند ناس معندهمش أي ألم — فالتقرير لوحده مش بيفسّر الألم دايمًا.\n\nخرافة: "الانحناء وشيل الحاجات خطر على الضهر". الضهر متصمم إنه ينحني ويشيل، والمهم التدرّج في الحمل وبناء القوة، مش الخوف من الحركة. خرافة: "الألم الشديد معناه ضرر كبير". شدة الألم مش دايمًا بتعكس حجم الإصابة، وبتتأثر بالنوم والتوتر والخوف. وأغلب نوبات ألم الضهر بتتحسن بشكل كبير خلال أسابيع.\n\nلكن فيه علامات خطر محتاجة طبيب فورًا: تنميل في منطقة المقعدة أو حوالين الأعضاء التناسلية، أو صعوبة في التحكم في البول أو البراز (طوارئ)، ضعف بيزيد في الرجلين، سخونية، تاريخ ورم، إصابة شديدة، نزول وزن غير مبرر، أو ألم ليلي مستمر مش بيتحسن بالراحة. وأي ألم مستمر أكتر من كام أسبوع يستاهل تقييم متخصص.',
    bodyEn: 'Myth: "bed rest is the cure". In fact, prolonged bed rest delays recovery; staying active within tolerable pain is better. Myth: "I need an MRI to find the cause". In most cases without red flags, imaging does not change treatment, and findings such as "disc bulges" or "degeneration" are very common in people with no pain at all — so a report alone does not always explain the pain.\n\nMyth: "bending and lifting are dangerous for the back". The back is designed to bend and lift; what matters is gradual loading and building strength, not fear of movement. Myth: "severe pain means serious damage". Pain intensity does not always reflect the extent of injury, and it is influenced by sleep, stress and fear. Most episodes of back pain improve substantially within weeks.\n\nHowever, some red flags need a doctor urgently: numbness in the saddle area or around the genitals, or difficulty controlling the bladder or bowels (an emergency), progressive leg weakness, fever, a history of cancer, significant trauma, unexplained weight loss, or persistent night pain not relieved by rest. Any pain lasting more than a few weeks deserves a specialist assessment.'
  },
  {
    specialty: 'physio',
    category: 'protocol',
    title: 'إدارة الحمل في مشاكل الأوتار المزمنة (Tendinopathy)',
    titleEn: 'Load management for tendinopathy',
    body: 'الأوتار بتتعب لما الحمل عليها يزيد أسرع من قدرتها على التأقلم — زي زيادة مفاجئة في الجري أو النط أو تغيير في الحذاء أو الأرضية. والعلاج الأساسي مش الراحة التامة (اللي بتضعّف الوتر أكتر) ولا إنك تكمل عادي، لكن "إدارة الحمل": تقليل الأنشطة اللي بتهيّج الوتر مؤقتًا، مع برنامج تقوية متدرج للوتر والعضلة (أحيانًا يبدأ بتمارين ثبات وبعدين تمارين أبطأ وأتقل وبعدين تمارين سرعة ونط).\n\nطريقة عملية لمتابعة الحمل: ألم خفيف أثناء التمرين ممكن يكون مقبول (الأخصائي بيحدد الحد، غالبًا في حدود 3-4 من 10)، بشرط إنه يهدى خلال 24 ساعة ومايزيدش الصبح اللي بعده. لو الألم أو التيبس زاد في اليوم التالي، يبقى الحمل كان أكتر من اللازم ونرجع خطوة. التحسن بياخد عادة أسابيع لشهور، والأجهزة والحقن ممكن تساعد في تقليل الألم لكنها مش بديل عن التمرين.\n\nعلامة خطر: إحساس "طقة" أو ضربة مفاجئة في الوتر (خصوصًا وتر أكيلس) مع ضعف مفاجئ — زي عدم القدرة على الوقوف على أطراف الصوابع — ممكن يكون قطع ومحتاج كشف عاجل. وحقن الكورتيزون في الأوتار قرار طبي بحت لأن ليها مخاطر على الوتر نفسه.',
    bodyEn: 'Tendons become painful when the load on them rises faster than their ability to adapt — for example a sudden increase in running or jumping, or a change of footwear or surface. The core treatment is neither complete rest (which weakens the tendon further) nor carrying on as usual, but "load management": temporarily reducing the activities that irritate the tendon, alongside a progressive strengthening programme for the tendon and muscle (sometimes starting with isometric holds, then slower, heavier exercises, then speed and jumping work).\n\nA practical way to monitor load: mild pain during exercise may be acceptable (the clinician sets the limit, often around 3–4 out of 10), provided it settles within 24 hours and is not worse the next morning. If pain or stiffness is worse the following day, the load was too much and we step back. Improvement usually takes weeks to months; devices and injections may help reduce pain but do not replace exercise.\n\nRed flag: a sudden "snap" or feeling of being kicked in the tendon (especially the Achilles) with sudden weakness — such as being unable to stand on tiptoe — may be a rupture and needs urgent assessment. Corticosteroid injections into tendons are purely a medical decision, as they carry risks for the tendon itself.'
  },
  {
    specialty: 'physio',
    category: 'protocol',
    title: 'خشونة الركبة والتمرين',
    titleEn: 'Knee osteoarthritis and exercise',
    body: 'التمرين من أهم علاجات خشونة الركبة الأساسية حسب الإرشادات العالمية، مش حاجة لازم نبعد عنها. الغضروف بيتغذى بالحركة، والعضلات القوية (خصوصًا عضلة الفخذ الأمامية وعضلات الحوض) بتخفف الحمل على المفصل. البرنامج عادة بيجمع بين تمارين تقوية، وتمارين مرونة وحركة، ونشاط هوائي قليل التأثير زي المشي والعجلة الثابتة والسباحة أو التمرين في المية، مع إنقاص الوزن لو زايد لأن كل كيلو بيفرق على الركبة.\n\nالألم الخفيف أثناء التمرين مقبول غالبًا لو هادي خلال 24 ساعة ومفيش تورّم زايد في اليوم التالي — لو حصل، بنعدّل الحمل مش بنبطّل. التدرّج هو الأساس، والتحسن في الألم والوظيفة بياخد عادة من 6 لـ12 أسبوع من الالتزام.\n\nارجع لطبيب لو: الركبة سخنة وحمرا ومتورمة فجأة (خصوصًا مع سخونية)، أو فيه "قفلة" في المفصل أو إحساس إن الركبة بتخون، أو ألم ليلي شديد، أو تدهور سريع في القدرة على المشي. والمسكنات والحقن قرار الطبيب، وبتكون مساعدة للتمرين مش بديل عنه.',
    bodyEn: 'According to international guidelines, exercise is one of the core first-line treatments for knee osteoarthritis, not something to avoid. Cartilage is nourished by movement, and strong muscles (especially the front thigh muscles and hip muscles) reduce the load on the joint. A programme usually combines strengthening, flexibility and mobility work, and low-impact aerobic activity such as walking, stationary cycling, swimming or water-based exercise, plus weight loss if needed, since every kilogram makes a difference to the knee.\n\nMild pain during exercise is usually acceptable if it settles within 24 hours with no increase in swelling the next day — if it does not, we adjust the load rather than stop. Gradual progression is key, and improvements in pain and function typically take 6 to 12 weeks of consistent effort.\n\nSee a doctor if the knee suddenly becomes hot, red and swollen (especially with a fever), if the joint locks or gives way, if there is severe night pain, or if walking ability deteriorates rapidly. Painkillers and injections are the doctor\'s decision and support exercise rather than replace it.'
  },

  /* ==================== أخصائي تأهيل ==================== */
  {
    specialty: 'rehab',
    category: 'education',
    title: 'ألم العضلات المتأخر (DOMS) ولا إصابة؟',
    titleEn: 'Delayed-onset muscle soreness (DOMS) or an injury?',
    body: 'ألم العضلات المتأخر بيظهر بعد تمرين جديد أو أتقل من المعتاد (خصوصًا النزول والتمارين اللا مركزية)، وبيبدأ بعد 12-24 ساعة، ويوصل لأقصاه في يوم أو اتنين، ويروح خلال كام يوم. بيكون ألم عام منتشر في العضلة كلها، غالبًا في الناحيتين، وبيخف مع الحركة والإحماء. ده رد فعل طبيعي وبيقل مع التعود، ومش مقياس لجودة التمرين.\n\nالإصابة ليها شكل مختلف: ألم حاد أو "شكة" مفاجئة في لحظة معينة أثناء التمرين، في نقطة محددة وفي ناحية واحدة، ومعاه أحيانًا تورّم أو زرقان أو ضعف واضح أو عدم قدرة على تكملة الحركة، وبيزيد مع الحركة بدل ما يخف. ده محتاج وقف النشاط وتقييم.\n\nعلامة خطر نادرة لكن مهمة: بعد تمرين عنيف جدًا (خصوصًا لو جديد عليك أو في الحر)، ألم شديد جدًا غير متناسب وتورّم في العضلات وضعف، مع بول غامق زي لون الكولا أو الشاي — ده ممكن يكون تكسّر في العضلات (Rhabdomyolysis) ومحتاج طوارئ فورًا لأنه بيأثر على الكلى.',
    bodyEn: 'Delayed-onset muscle soreness appears after a new or heavier-than-usual session (especially downhill or eccentric work), starts 12–24 hours later, peaks within a day or two and fades over a few days. It is a general ache spread across the whole muscle, usually on both sides, and it eases with movement and warming up. It is a normal response that lessens as you adapt, and it is not a measure of how good the session was.\n\nAn injury looks different: a sharp pain or sudden "twinge" at a specific moment during exercise, in a specific spot on one side, sometimes with swelling, bruising, obvious weakness or inability to finish the movement, and it gets worse with movement rather than easing. This needs you to stop and be assessed.\n\nA rare but important red flag: after very hard exercise (especially if it is new to you or done in the heat), extreme, disproportionate muscle pain and swelling with weakness, together with dark urine the colour of cola or tea, may be muscle breakdown (rhabdomyolysis) and needs the emergency department immediately because it affects the kidneys.'
  },
  {
    specialty: 'rehab',
    category: 'protocol',
    title: 'الرجوع للرياضة بعد جراحة الرباط الصليبي — بالمعايير مش بالتاريخ',
    titleEn: 'Return to sport after ACL reconstruction — criteria, not the calendar',
    body: 'المقالة دي مكمّلة لمقالتي الرباط الصليبي ومراحل العودة للرياضة في المكتبة. الرجوع للرياضات اللي فيها لف وتغيير اتجاه بعد جراحة الرباط الصليبي بياخد عادة 9 شهور على الأقل، والأبحاث بتقول إن الرجوع بدري عن كده مرتبط بخطر أعلى لإعادة القطع. لكن الوقت لوحده مش كفاية — لازم الرياضي يعدّي معايير واضحة.\n\nمن المعايير اللي بتستخدم عادة: مدى حركة كامل ومفيش تورّم، قوة عضلة الفخذ الأمامية والخلفية قريبة جدًا من الرجل السليمة (غالبًا 90٪ أو أكتر)، نتايج كويسة في اختبارات النط على رجل واحدة، جودة حركة كويسة في الهبوط وتغيير الاتجاه من غير ما الركبة تميل لجوه، وجاهزية نفسية وثقة في الركبة. وبعدها رجوع تدريجي: تمرين مع الفريق بدون احتكاك، بعدين باحتكاك، بعدين ماتشات.\n\nخطر الإصابة التانية (في نفس الركبة أو التانية) عالي خصوصًا عند الرياضيين الصغيرين، عشان كده برامج الوقاية (تقوية، هبوط، توازن) بتكمل حتى بعد الرجوع. قرار الرجوع النهائي مشترك بين الجرّاح وأخصائي التأهيل والمدرب، ولو حصل تورّم جديد أو إحساس إن الركبة بتخون، ارجع للجرّاح.',
    bodyEn: 'This article complements the ACL and return-to-sport articles in the library. Returning to pivoting and cutting sports after ACL reconstruction usually takes at least 9 months, and research links returning earlier with a higher risk of re-rupture. But time alone is not enough — the athlete must pass clear criteria.\n\nCommonly used criteria include full range of motion with no swelling, front and back thigh strength very close to the uninjured leg (often 90% or more), good results on single-leg hop tests, good movement quality on landing and changing direction without the knee collapsing inwards, and psychological readiness and confidence in the knee. This is followed by a gradual return: non-contact team training, then contact training, then matches.\n\nThe risk of a second injury (to the same or the other knee) is high, especially in young athletes, so prevention programmes (strength, landing, balance) continue even after returning. The final return decision is shared between the surgeon, the rehab specialist and the coach, and any new swelling or feeling of the knee giving way means going back to the surgeon.'
  },
  {
    specialty: 'rehab',
    category: 'protocol',
    title: 'الوقاية من السقوط عند كبار السن',
    titleEn: 'Falls prevention in older adults',
    body: 'السقوط من أهم أسباب الكسور وفقدان الاستقلالية عند كبار السن، وأقوى وسيلة للوقاية منه هي برنامج تمارين منتظم بيجمع بين التوازن والتقوية (خصوصًا عضلات الرجلين والحوض)، بمعدل حوالي 3 مرات في الأسبوع أو أكتر، وبيتصعّب تدريجيًا لشهور. التمارين زي الوقوف من على الكرسي، الوقوف على رجل واحدة جنب سند، المشي على خط، والتاي تشي، أثبتت فايدتها — بشرط تبدأ بأمان وبإشراف في الأول.\n\nعوامل تانية مهمة: مراجعة الأدوية مع الطبيب أو الصيدلي (المنومات والمهدئات وبعض أدوية الضغط اللي بتعمل دوخة لما تقوم مرة واحدة)، الكشف على النظر، جزمة مقفولة ثابتة، إضاءة كويسة بالليل، شيل السجاجيد اللي بتتزحلق، ومسكات في الحمام. القيام بالراحة من السرير (اقعد شوية الأول) بيقلل دوخة الوقوف.\n\nبعد أي وقعة، حتى لو من غير إصابة واضحة، بلّغ الطبيب لأن الوقعة نفسها ممكن تكون علامة على مشكلة (دوخة، ضعف، دوا). روح الطوارئ فورًا لو: ألم في الفخذ أو الحوض مع عدم القدرة على الوقوف، خبطة في الراس خصوصًا مع أدوية السيولة، أو تلخبط أو ضعف مفاجئ.',
    bodyEn: 'Falls are a major cause of fractures and loss of independence in older adults, and the strongest prevention tool is a regular exercise programme combining balance and strength (especially leg and hip muscles), about 3 times a week or more, progressed gradually over months. Exercises such as sit-to-stand from a chair, standing on one leg next to a support, heel-to-toe walking and tai chi have proven benefit — provided they start safely and under supervision at first.\n\nOther important factors: a medication review with the doctor or pharmacist (sleeping pills, sedatives and some blood pressure medicines that cause dizziness on standing up quickly), an eye check, closed and stable footwear, good lighting at night, removing slippery rugs, and grab rails in the bathroom. Getting up slowly from bed (sit for a moment first) reduces dizziness on standing.\n\nAfter any fall, even without an obvious injury, tell the doctor, because the fall itself may signal a problem (dizziness, weakness, a medicine). Go to the emergency department immediately if there is hip or groin pain with inability to stand, a head injury (especially on blood thinners), or sudden confusion or weakness.'
  },

  /* ==================== أخصائي نفسي رياضي ==================== */
  {
    specialty: 'psychologist',
    category: 'education',
    title: 'النوم والاستشفاء',
    titleEn: 'Sleep and recovery',
    body: 'النوم مش وقت ضايع من التدريب — هو الوقت اللي الجسم بيصلّح فيه العضلات وبيرتّب فيه الهرمونات والمخ بيثبّت فيه المهارات اللي اتعلمتها. قلة النوم المزمنة مرتبطة بأداء أقل، رد فعل أبطأ، مزاج أسوأ، ومناعة أضعف، وبعض الدراسات بتربطها بزيادة خطر الإصابات. الكبار محتاجين عادة 7-9 ساعات، والمراهقين أكتر (حوالي 8-10).\n\nعادات بتساعد: مواعيد نوم وصحيان ثابتة قدر الإمكان حتى في الإجازات، أوضة ضلمة وهادية ومعتدلة الحرارة، تقليل الشاشات قبل النوم بساعة، تجنب الكافيين (قهوة، شاي، مشروبات طاقة، وبعض مكملات ما قبل التمرين) في الست ساعات اللي قبل النوم، وقيلولة قصيرة (20-30 دقيقة) لو محتاج بدل قيلولة طويلة. ليلة وحشة قبل المنافسة من القلق حاجة طبيعية ومش بتبوّظ الأداء لوحدها — المهم النوم في الأيام اللي قبلها. في رمضان، تنظيم النوم حوالين السحور ومواعيد التمرين بيفرق كتير.\n\nاستشير طبيب لو: شخير عالي مع توقف في النفس بيلاحظه حد جنبك، نعاس شديد بالنهار رغم النوم الكافي، أرق مستمر لأسابيع، أو حركة لا إرادية مزعجة في الرجلين بالليل. ومتاخدش منومات من غير استشارة، لأن بعضها بيأثر على الأداء والتوازن في اليوم التالي.',
    bodyEn: 'Sleep is not time lost from training — it is when the body repairs muscle, regulates hormones, and when the brain consolidates the skills you practised. Chronic sleep loss is linked to lower performance, slower reactions, worse mood and weaker immunity, and some studies link it to a higher injury risk. Adults usually need 7–9 hours, and adolescents more (around 8–10).\n\nHabits that help: consistent sleep and wake times as far as possible, even on days off; a dark, quiet, comfortably cool room; reducing screens for an hour before bed; avoiding caffeine (coffee, tea, energy drinks and some pre-workout supplements) in the six hours before bed; and a short nap (20–30 minutes) if needed rather than a long one. A poor night before competition because of nerves is normal and does not ruin performance on its own — sleep in the preceding days matters more. During Ramadan, organising sleep around suhoor and training times makes a big difference.\n\nConsult a doctor if there is loud snoring with pauses in breathing noticed by someone else, severe daytime sleepiness despite enough sleep, insomnia lasting weeks, or uncomfortable restless legs at night. Do not take sleeping pills without advice, as some affect performance and balance the next day.'
    },
  /* ==================== من موظف التطوير — مسودة لازم الطبيب يراجعها ==================== */
  {
    specialty: 'sports_medicine',
    category: 'education',
    title: 'تمرين المقاومة وصحة المخ مع التقدم في السن',
    titleEn: 'Resistance training and brain health with ageing',
    body: 'تمرين المقاومة (الأوزان أو الأستك أو وزن الجسم) مش بس للعضلات. مراجعات أبحاث كتير على الناس فوق ٥٠ سنة لقت إن التمرين المنتظم — ومنه تمرين المقاومة — مرتبط بتحسن بسيط لمتوسط في وظائف زي التركيز والتخطيط والذاكرة، وفيه أبحاث جديدة بتدرس أثره على علامات شيخوخة المخ نفسها.\n\nالعملي من ده: مرتين لتلاتة في الأسبوع، تمارين للعضلات الكبيرة (رجل وضهر وصدر)، وزيادة الحمل تدريجيًا، مع إشراف في الأول لكبار السن أو اللي عندهم أمراض مزمنة. الفايدة بتيجي من الاستمرار شهور مش أسابيع.\n\nده تثقيف عام ومش علاج لأي مرض في الذاكرة أو المخ — أي نسيان أو تغيّر في التركيز محتاج كشف عند الطبيب.\n\n(مسودة من موظف التطوير — المصدر اللي اتبنت عليه: Geroscience، تجربة عشوائية عن تمرين المقاومة وساعات شيخوخة المخ. الطبيب يراجع النتائج ويعدّل الكلام قبل الموافقة.)',
    bodyEn: 'Resistance training (weights, bands or bodyweight) is not only about muscle. Many research reviews in people over 50 have linked regular exercise — including resistance training — with small-to-moderate improvements in abilities such as attention, planning and memory, and newer studies are looking at its effect on markers of brain ageing itself.\n\nIn practice: two to three sessions a week, working the big muscle groups (legs, back, chest), increasing the load gradually, with supervision at first for older adults or anyone with a chronic condition. The benefit comes from keeping it up for months, not weeks.\n\nThis is general education, not treatment for any memory or brain condition — any forgetfulness or change in concentration needs a doctor\'s assessment.\n\n(Draft from the R&D assistant — based on: Geroscience, a randomized controlled trial of resistance exercise and brain ageing clocks. The doctor should check the findings and edit before approving.)'
  }
];
